### ISSUE TITLE
New Standard: NFT metadata

### ISSUE THREAD

**Issue by psiemens** [onflow/flip-fest#16] opened 2021-09-12 07:26 UTC
<p align="center">
  <img  height="300" src="https://user-images.githubusercontent.com/901466/146048771-5d0b847a-cb9f-46d8-ba39-766a94444048.png">
</p>

> 👋  &nbsp; If you are interested in working on this issue, please check out the [Getting Started guide on HackerEarth](https://www.hackerearth.com/challenges/hackathon/flip-fest/custom-tab/getting-started/#Getting%20Started)!

## Description (Problem Statement)

NFTs are more than just numbers and bytes — at their best, they are rich representations of digital goods that people around the world can fall in love with. The current Flow NFT interface, however, does not include a metadata standard that allows these representations to flourish. NFTs should be able to include structured data, images, videos and other types of data. What modifications should be made to the NFT interface to support a variety of metadata types?

The Flow community has been [discussing an NFT metadata standard over the past several months](https://github.com/onflow/flow-nft/issues/9), with representation from many of the NFT applications currently live on mainnet. In recent weeks, several developers have created a concrete proposal that has gained support from the broader ecosystem. We'd love for those developers to formalize their standard and launch it as part of the Flow FLIP Fest.

This ticket is a special one. Most of the groundwork has already been done, and we're hoping that the FLIP Fest can act as the catalyst that brings that work to life. The core Flow team has reached out to the developers who are already actively engaging in this problem, but we also welcome new contributions. This isn't a winner takes all bounty — we'll be issuing rewards to the people who make the most meaningful contributions to the final standard.

## Minimum Feature Set (Acceptance Criteria)

*Metadata Type Structure*

The standard itself should define a generic type structure that allows a variety of metadata types to be defined directly in Cadence. This standard should be implemented in Cadence as an extension of the current [NFT standard](https://github.com/onflow/flow-nft).

*Metadata Type Examples*

With the introduction of a new standard, it's important that developers know how to use it. Your final submission should include examples of common uses cases that demonstrate 6-12 different data types. For example:

- Bitmap images (e.g. JPEG, PNG)
- Vector images (e.g. SVG)
- Videos
- Metadata that is stored in a decentralized storage storage network (e.g. IPFS)

## Milestone Requirements

1. Define a rough outline of your proposal. This can be a written document (i.e. a GitHub issue), but should also include Cadence code snippets that illustrate the core concepts of the standard.
2. Document your metadata as a [Flow Improvement Proposal (FLIP)](https://github.com/onflow/flow/tree/master/flips).
3. Using feedback from those who review your FLIP, make any necessary changes and work with the reviewers to merge a finalized FLIP.
4. After the FLIP is approved, open a pull request into the Flow NFT repository that contains the following:
    1. Your extension to the existing NFT standard.
    2. 6-12 sample metadata implementations.

## Judging Criteria

- For all projects, [technical & high-level judging criteria apply](https://github.com/onflow/flip-fest/blob/main/resources/judging-criteria.md).
- Flexibility — does your solution support a wide variety of NFT metadata use cases?
- Extensibility — can your standard be extended to support future use cases?

## Resources

- [Flow NFT Standard](https://github.com/onflow/flow-nft)
- [Flow Improvement Proposals documentation](https://github.com/onflow/flow/tree/master/flips)
- [Existing NFT metadata discussion](https://github.com/onflow/flow-nft/issues/9)

**Comment by rheaplex** [comment] 2021-09-15 19:14
Heya everyone!

I'm Rhea, one of the engineers from the core Flow team working on Cadence and its uses. As you can see from the Assignees list I'm a point of contact for all of you on this issue. I write Cadence code and perform code reviews for internal and external projects, so if you have any Cadence questions I should be able to help! In a previous life I did metadata standards work, so I'm looking forward to seeing what comes from this initiative.

😺

**Comment by joshuahannan** [comment] 2021-09-15 19:24
Hello! My name is Josh and I am also a smart contract engineer on the Flow team. I'm happy to help wherever is needed. 😄

**Comment by bjartek** [comment] 2021-09-15 20:16
👋

**Comment by briandilley** [comment] 2021-09-15 20:52
👋 as NFTco (along with @bjartek).

**Comment by briandilley** [comment] 2021-09-15 21:42
Team _**Non Fungibles**_ checking in on this one:
- @bjartek 
- @bluedesign
- @briandilley  

First milestone (FLIP submission) should be done today/tomorrow.

**Comment by CharlesM1nD** [comment] 2021-09-16 12:15
Your team name with a link to the HackerEarth team
https://www.hackerearth.com/challenges/hackathon/flip-fest/dashboard/2f5b51c/team/

Tag all team members with their Github usernames that are working on the project：
https://github.com/cata-network

When you plan on completing the first milestone.
2021.10.10

**Comment by gotisbrown** [comment] 2021-09-16 16:32
Hi, all: I'm Glenn. Here to help on this proposal along with Rhea and co. Looking forward to it.

**Comment by figs999** [comment] 2021-09-16 19:48
Solo Team here. First Milestone has been submitted to HackerEarth.
https://www.hackerearth.com/challenges/hackathon/flip-fest/dashboard/4459c1a/team/

**Comment by figs999** [comment] 2021-09-17 18:54
I have just submitted a flip, completing Milestone 2.

**Comment by briandilley** [comment] 2021-09-17 19:11
Team _**[Non Fungibles](https://www.hackerearth.com/challenges/hackathon/flip-fest/dashboard/3744a70/team/)**_ checking in again. 

PR for Milestone 1: https://github.com/onflow/flow/pull/636

**Comment by figs999** [comment] 2021-09-17 19:35
> Team _**[Non Fungibles](https://www.hackerearth.com/challenges/hackathon/flip-fest/dashboard/3744a70/team/)**_ checking in again.
> 
> PR for Milestone 1: [onflow/flow#636](https://github.com/onflow/flow/pull/636)

FYI, the flip PR is Milestone 2! You guys are further along than you're giving yourself credit for ;)
Looks like you still need to do the Milestone 1 and 2 PRs into this repo, though?

**Comment by briandilley** [comment] 2021-09-17 19:48
> FYI, the flip PR is Milestone 2! You guys are further along than you're giving yourself credit for ;)

haha - yeah, I'm getting confused as to what to do.

**Comment by briandilley** [comment] 2021-09-17 19:49
Oh, it seems that we've done Milestone #1 a long time ago (before flip-fest was announced really), and our FLIP pretty much covers it too.

**Comment by bjartek** [comment] 2021-09-17 19:50
Yeah i think we can just point to the old issue in the nft repo for our milestone 1.

**Comment by srinjoyc** [comment] 2021-09-17 20:11
Hey guys, so for the PRs we're hoping to track them all on one repo so to help us out, could you do the following:
- Fork this repo
- Create a branch and PR with a single file called: submissions/issue-16/milestone-1/non-fungibles
- In the file, you can include the same info as the PR description (just copy/paste) - [PR Template]
(https://github.com/onflow/flip-fest/blob/main/pull_request_template.md) for reference.

For milestone 2, you'd do the same thing, except change branch and file name. Once your milestone 1 has been approved, you can submit milestone 2. In this case, it's fine if you open both at the same time since we know you had this work done beforehand but just FYI in the future.

Sorry for the bit of extra work, but really helps out with tracking! Let me know if you have any other q's.

**Comment by briandilley** [comment] 2021-09-17 21:10
cool, no problem. Is there a single place where the documentation for all
of this is? I may be contributing to another issue as well.

Here's the PR for the work on #16:
https://github.com/onflow/flip-fest/pull/35

**Comment by figs999** [comment] 2021-09-17 23:28
Ok, I think I did the Milestone 2 PR wrong before by just pushing to the same PR as Milestone 1...
I just opened a new PR for Milestone 2: https://github.com/onflow/flip-fest/pull/36

**Comment by figs999** [comment] 2021-09-20 22:35
> Hey guys, so for the PRs we're hoping to track them all on one repo so to help us out, could you do the following:
> 
> * Fork this repo
> * Create a branch and PR with a single file called: submissions/issue-16/milestone-1/non-fungibles
> * In the file, you can include the same info as the PR description (just copy/paste) - [PR Template](https://github.com/onflow/flip-fest/blob/main/pull_request_template.md) for reference.
> 
> For milestone 2, you'd do the same thing, except change branch and file name. Once your milestone 1 has been approved, you can submit milestone 2. In this case, it's fine if you open both at the same time since we know you had this work done beforehand but just FYI in the future.
> 
> Sorry for the bit of extra work, but really helps out with tracking! Let me know if you have any other q's.

I just noticed that I am not being tracked in the approved teams of the project. Is there a reason for that ommission?

**Comment by psiemens** [comment] 2021-09-21 06:33
Sorry @figs999! You are being tracked there. We don't have separate issues for each team, so you are included on this one.

**Comment by psiemens** [comment] 2021-09-21 06:41
Thanks for the great submissions @figs999 and @briandilley. We're going to take a couple days to gather reviews for your FLIPs, but both teams have been approved for milestone 1. 🎉

**Comment by zikunfan** [comment] 2021-09-26 02:50
Crust Pinner Team here.
https://www.hackerearth.com/challenges/hackathon/flip-fest/dashboard/dbc0820/team/view/

Team name is: Crust Pinner
Will working on NFT Decentralized Storage.

**Comment by psiemens** [comment] 2021-09-28 18:23
Hey everybody! I'd like to introduce you to [Glenn Brown](https://www.linkedin.com/in/gotisbrown/) (@gotisbrown) -- he's an advisor for the Flow ecosystem looking into how the new metadata standard can be adopted by projects across Flow. Glenn used to be CEO of Creative Commons and has done a lot of standards work in the past. 😄 

We'd love to set up time for each team to chat with Glenn about their solutions, and in particular, how they can be used to solve further problems like NFT rights and royalties. 

- Coelacanth: @figs999 
- Non Fungibles: @bjartek @bluesign @briandilley
- Crust Pinner: @nghianguyen119 @zikunfan

If you're interested, could somebody from each team please send me an email (peter@dapperlabs.com) or a Discord DM (`pete#0003`)? Then we can coordinate a meeting!

**Comment by njuyuanrui** [comment] 2021-10-10 17:39
> Your team name with a link to the HackerEarth team https://www.hackerearth.com/challenges/hackathon/flip-fest/dashboard/2f5b51c/team/
> 
> Tag all team members with their Github usernames that are working on the project： https://github.com/cata-network
> 
> When you plan on completing the first milestone. 2021.10.10

Hello~ First of all, sorry that the previous registration seems to have failed :(
But we have been working on it until now~~
Our milestone 1 is [here](https://github.com/onflow/flip-fest/pull/61)

We introduced some design points about metadata standards which might provide some help for the construction and optimization of other solutions. And we also gave our initial solution here.

We welcome your suggestions! 
Thank you~

**Comment by kimcodeashian** [comment] 2021-11-13 00:02
Good day @bluesign, @figs999!

Thanks so much for all your hardwork & participation. In order to finalize winners & prepare for prize payout, we'll need the following actions from your end.

Please provide the following information by **Nov 17, 2021**,  (in this GH Issue is fine): 

**1. Team Information**
  - Team Members Information - Github Username + Email Contact + Percentage of prize allocation (total should = 100%) 
  - All mentioned members MUST react to the post with a 👍 which will act as confirmation that the information is correct, or a 👎 to indicate that the information is not correct.
  - We will be reaching out via e-mail

**🎖IMPORTANT**: We will only proceed with prize payouts once all members have confirmed with 👍 on the post. 


**2. Video Demo (optional)**
  - Please provide a 5-minute video demo to be featured & showcased in the FLIP Fest Closing Ceremonies
  - Link format & Downloadable (eg. Google Drive, Vimeo)
  - Content Format (Problem Statement, your work / how you solved it, final outcome) 
 

We will be hosting Closing Ceremonies on November 23rd, 8AM PT where we'll having closing remarks from Dete & will be announcing the winners! I'll share the details here before Nov 17.

**Comment by figs999** [comment] 2021-11-13 01:55
My team is solo, so it’s just me: 
@figs999 (figs999@gmail.com) ~ 100%

**Comment by qq976739120** [comment] 2021-11-13 09:19
My team is solo, so it’s just me:
@qq976739120  (976739120@qq.com) ~ 100%

**Comment by bluesign** [comment] 2021-11-13 19:12
hey Kim, 

@bjartek bjarte.stien.karlsen@gmail.com 33%
@bluesign deniz@edincik.com 33%
@briandilley brian@nftco.com  34%

**Comment by kimcodeashian** [comment] 2021-11-17 01:19
Hey folks,

We've received and reviewed over **82 submissions**! What an amazing community on Flow! To commemorate all the hard work done, we have finalized winners and will be announcing them during our **[Closing Ceremony](https://forms.gle/j9REJJkVtFFibtfR8) on Nov 23rd, 8AM PT**. Be sure to join us - there may be some attendance prizes & a keynote from our CTO, Dete 😉!  

**[RSVP here](https://forms.gle/j9REJJkVtFFibtfR8)** so you don't miss out! See you then!

**Comment by njuyuanrui** [comment] 2021-11-17 06:01
My team is solo, so it's just me:
@njuyuanrui njuyuanrui@163.com  100%

**Closed** 2021-12-15 19:23 UTC
Labels: Tier 1, FLIP

**Comment by Marcitpro** [comment] 2023-10-17 06:26
There's been a lot going on in NFTs lately. I recently started following this topic to learn how to flip nft. It is possible to make money in this industry. But you have to stay up to date. That's why I recommend [this post](https://nftmonk.com/learn-how-to-flip-nfts-and-make-profit-in-the-digital-art-market/) because it's really well written.
